package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScheme<M extends BaseScheme<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setScheme(java.lang.String scheme) {
		set("scheme", scheme);
	}
	
	public java.lang.String getScheme() {
		return getStr("scheme");
	}

	public void setSchemetype(java.lang.Integer schemetype) {
		set("schemetype", schemetype);
	}
	
	public java.lang.Integer getSchemetype() {
		return getInt("schemetype");
	}

	public void setSchemetime(java.lang.String schemetime) {
		set("schemetime", schemetime);
	}
	
	public java.lang.String getSchemetime() {
		return getStr("schemetime");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

}
